spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ahp?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&useSSL=false
    username: root
    password: zkj12138110
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 1000MB # 设置单个文件的大小为10M
      max-request-size: 1000MB # 设置总上传的数据大小为50M
  redis:
    host: localhost
    port: 6379
    password: root123456
    lettuce:
      pool:
        max-wait: 100 #连接等待时间
        max-idle: 8 #最大空闲连接
        min-idle: 0 #最小空闲连接
        max-active: 10 #最大连接
  # 设置文件编码为UTF-8
  file:
    encoding: UTF-8
  # 设置时区为GMT+08:00
  user:
    timezone: GMT+08
  jackson:
    date-format: yyyy-mm-dd hh:mm:ss

## 设置日志级别
#logging:
#  level:
#    root: OFF

server:
  port: 8836

mybatis:
  mapper-locations: classpath:mapper/*.xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

my-app-properties:
  minio:
    endpoint: http://1.12.49.85:9000
    accessKey: minioadmin
    secretKey: minioadmin



